Repository rdmorganiser/rdmo, pull requests merged in 2023-12, with the labels that each got.

#839 build: batch update javascript dependencies
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  package-lock.json
  package.json
  rdmo/management/tests/test_frontend.py
Labels: type:maintenance, dependencies, javascript

#857 fix: add required dependency packaging
  pyproject.toml
Labels: type:bug

#859 858 filter in managment should be case insensitive
  rdmo/management/assets/js/utils/filter.js
Labels: javascript

#856 ci: add current git sha to version in build-wheel job
  .github/workflows/ci.yml
  rdmo/__init__.py
Labels: type:maintenance

#862 ci: add dependency tree to step summary of optional-dependencies job
  .github/workflows/ci.yml
  pyproject.toml
Labels: type:maintenance

#877 ci: run build-wheel job on main and prs
  .github/workflows/ci.yml
Labels: type:maintenance
