Repository rdmorganiser/rdmo, pull requests merged in 2023-07, with the labels that each got.

#627 Add feature flag for translation of empty fields
  rdmo/core/models.py
  rdmo/core/settings.py
  rdmo/core/tests/test_models.py
Labels: status: agreed

#635 Implement alternate shibboleth setup
  rdmo/accounts/templates/account/login_form.html
  rdmo/accounts/tests/test_views.py
  rdmo/accounts/urls/__init__.py
  rdmo/accounts/views.py
  rdmo/core/settings.py
  rdmo/core/views.py
Labels: status: acceptance

#642 Dev 1.11.0 requirements django-allauth 0.53.1
  requirements.txt
Labels: type: maintainance

#631 Add invite api (#540)
  rdmo/accounts/settings.py
  rdmo/projects/managers.py
  rdmo/projects/models/invite.py
  rdmo/projects/serializers/v1/__init__.py
  rdmo/projects/tests/test_commands.py
  rdmo/projects/tests/test_view_membership.py
  rdmo/projects/tests/test_view_project.py
  rdmo/projects/tests/test_viewset_invite.py
  rdmo/projects/tests/test_viewset_project.py
  rdmo/projects/tests/test_viewset_project_invite.py
  rdmo/projects/urls/v1.py
  rdmo/projects/utils.py
  rdmo/projects/views/membership.py
  rdmo/projects/viewsets.py
  testing/fixtures/projects.json
Labels: status: work in progress

#651 bug fix for typo in tasks modal form
  rdmo/tasks/templates/tasks/tasks_modal_form_tasks.html
Labels: type: bug
