Repository rdmorganiser/rdmo, pull requests merged in 2023-09, with the labels that each got.

#700 ci: add python 3.12-dev test run in ci
  .github/workflows/pytest.yml
  pyproject.toml
Labels: type: maintenance

#705 chore: remove obsolete dependency "pytest-dotenv"
  pyproject.toml
Labels: type: maintenance

#706 chore: remove obsolete dependency "jsonfield"
  pyproject.toml
  rdmo/accounts/migrations/0001_initial.py
  rdmo/accounts/migrations/0003_hint_renamed_to_help_text.py
Labels: type: maintenance

#689 chore: add eslint pre-commit hook
  .eslintrc.js
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  rdmo/core/tests/test_project_status.py
  webpack/common.config.js
Labels: type: maintenance

#693 chore: update python dependencies
  .github/workflows/pytest.yml
  pyproject.toml
  rdmo/accounts/forms.py
  rdmo/conditions/migrations/0025_alter_condition_editors.py
  rdmo/core/settings.py
  rdmo/domain/migrations/0050_alter_attribute_editors.py
  rdmo/options/migrations/0032_alter_option_editors_alter_optionset_editors.py
  rdmo/projects/forms.py
  rdmo/projects/views/membership.py
  rdmo/questions/migrations/0091_alter_catalog_editors_alter_page_editors_and_more.py
  rdmo/tasks/migrations/0036_alter_task_editors.py
  rdmo/views/migrations/0029_alter_view_editors.py
  testing/config/settings/base.py
  testing/config/settings/mysql.py
  testing/config/settings/postgres.py
  testing/config/settings/sqlite3.py
Labels: type: maintenance

#710 ci: add webpack-build job
  .github/workflows/ci.yml
  README.md
Labels: type: maintenance

#707 Add SITE_ID, DEBUG_TOOLBAR, ALLOWED_HOSTS, and BASE_URL to settings
  pyproject.toml
  rdmo/core/settings.py
Labels: type: maintenance

#711 chore: use major.minor.patch constraint for 0 major version dependencies
  pyproject.toml
Labels: type: maintenance

#712 docs: add compare urls to changelog
  CHANGELOG.md
Labels: type: documentation

#748 fix: rename label in feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type:maintenance

#750 Fix CITATION.cff
  CITATION.cff
Labels: type:maintenance

#749 Update settings
  testing/config/settings/base.py
Labels: type:maintenance
