Repository rdmorganiser/rdmo, pull requests merged in 2023-11, with the labels that each got.

#778 docs: add additional badges to readme
  README.md
Labels: type:documentation

#813 chore: update ruff repo name in pre-commit config
  .pre-commit-config.yaml
Labels: type:maintenance

#679 Refactor progress bar and overview
  .eslintrc.js
  rdmo/core/static/core/js/core.js
  rdmo/projects/managers.py
  rdmo/projects/migrations/0059_project_progress.py
  rdmo/projects/models/project.py
  rdmo/projects/permissions.py
  rdmo/projects/progress.py
  rdmo/projects/rules.py
  rdmo/projects/serializers/v1/overview.py
  rdmo/projects/serializers/v1/page.py
  rdmo/projects/static/projects/css/project_questions.scss
  rdmo/projects/static/projects/js/project_questions/services.js
  rdmo/projects/templates/projects/project_detail_header_hierarchy.html
  rdmo/projects/templates/projects/project_questions_navigation.html
  rdmo/projects/templates/projects/project_questions_navigation_help.html
  rdmo/projects/templates/projects/project_questions_progress.html
  rdmo/projects/templates/projects/projects.html
  rdmo/projects/templates/projects/site_projects.html
  rdmo/projects/templatetags/projects_tags.py
  rdmo/projects/tests/test_navigation.py
  rdmo/projects/tests/test_progress.py
  rdmo/projects/tests/test_viewset_project.py
  rdmo/projects/tests/test_viewset_project_progress.py
  rdmo/projects/viewsets.py
Labels: status:acceptance

#769 test: add front-end tests for react code
  .github/workflows/ci.yml
  conftest.py
  pyproject.toml
  rdmo/management/tests/test_frontend.py
  testing/config/settings/base.py
Labels: type:maintenance, status:acceptance

#812 ci: add build-wheel job
  .github/workflows/ci.yml
Labels: type:maintenance

#834 ci: add dependency groups to dependabot config
  .github/dependabot.yml
Labels: type:maintenance

#772 Refactor autocomplete
  rdmo/core/settings.py
  rdmo/projects/static/projects/js/project_questions/services.js
  rdmo/projects/templates/projects/project_questions_element.html
  rdmo/projects/templates/projects/project_questions_form_group_autocomplete.html
  rdmo/projects/views/project.py
  rdmo/projects/widgets.py
  rdmo/questions/constants.py
Labels: status:acceptance

#765 Fix grammar
  rdmo/locale/de/LC_MESSAGES/django.po
  rdmo/management/assets/js/components/edit/EditPage.js
  rdmo/management/assets/js/components/edit/EditQuestion.js
  rdmo/management/assets/js/components/edit/EditQuestionSet.js
  rdmo/projects/serializers/v1/page.py
  rdmo/projects/templates/projects/project_questions_add_field_button.html
  rdmo/projects/templates/projects/project_questions_add_field_help.html
  rdmo/projects/templates/projects/project_questions_add_set_button.html
  rdmo/projects/templates/projects/project_questions_add_set_help.html
  rdmo/projects/templates/projects/project_questions_modal_delete_valuesets.html
  rdmo/projects/templates/projects/project_questions_modal_form_valuesets.html
  rdmo/projects/templates/projects/project_questions_questionset_head.html
  rdmo/projects/templates/projects/project_questions_questionset_head_help.html
  rdmo/projects/templates/projects/project_questions_remove_field.html
  rdmo/projects/templates/projects/project_questions_remove_set.html
  rdmo/questions/imports.py
  rdmo/questions/migrations/0092_remove_verbose_name_plural.py
  rdmo/questions/models/page.py
  rdmo/questions/models/question.py
  rdmo/questions/models/questionset.py
  rdmo/questions/renderers/mixins.py
  rdmo/questions/serializers/export.py
  rdmo/questions/serializers/v1/page.py
  rdmo/questions/serializers/v1/question.py
  rdmo/questions/serializers/v1/questionset.py
  rdmo/questions/templates/questions/export/page.html
  rdmo/questions/templates/questions/export/question.html
  rdmo/questions/templates/questions/export/questionset.html
  rdmo/questions/tests/test_viewset_page.py
  rdmo/questions/tests/test_viewset_page_multisite.py
  rdmo/questions/tests/test_viewset_question.py
  rdmo/questions/tests/test_viewset_question_multisite.py
  rdmo/questions/tests/test_viewset_questionset.py
  rdmo/questions/tests/test_viewset_questionset_multisite.py
  testing/fixtures/questions.json
Labels: status:agreed, migrations

#831 Order tasks/issues an views in projects
  rdmo/management/assets/js/components/edit/EditTask.js
  rdmo/management/assets/js/components/edit/EditView.js
  rdmo/management/assets/js/components/element/Task.js
  rdmo/management/assets/js/components/elements/Tasks.js
  rdmo/projects/migrations/0060_alter_issue_options.py
  rdmo/projects/models/issue.py
  rdmo/projects/templates/projects/project_detail_views.html
  rdmo/projects/views/project.py
  rdmo/tasks/imports.py
  rdmo/tasks/migrations/0036_task_order.py
  rdmo/tasks/models.py
  rdmo/tasks/renderers/mixins.py
  rdmo/tasks/serializers/export.py
  rdmo/tasks/serializers/v1.py
  rdmo/views/imports.py
  rdmo/views/migrations/0029_view_order.py
  rdmo/views/models.py
  rdmo/views/renderers/mixins.py
  rdmo/views/serializers/export.py
  rdmo/views/serializers/v1.py
Labels: migrations

#770 Refactor options
  rdmo/core/static/core/css/base.scss
  rdmo/core/static/core/css/utils.scss
  rdmo/core/xml.py
  rdmo/management/assets/js/actions/configActions.js
  rdmo/management/assets/js/api/OptionsApi.js
  rdmo/management/assets/js/components/edit/EditOption.js
  rdmo/management/assets/js/components/edit/common/Radio.js
  rdmo/management/assets/scss/management.scss
  rdmo/management/tests/test_import_options.py
  rdmo/options/imports.py
  rdmo/options/migrations/0032_alter_option_additional_input.py
  rdmo/options/migrations/0033_option_help.py
  rdmo/options/migrations/0034_option_view_text.py
  rdmo/options/models.py
  rdmo/options/renderers/mixins.py
  rdmo/options/serializers/export.py
  rdmo/options/serializers/v1/option.py
  rdmo/options/templates/options/export/option.html
  rdmo/options/urls/v1.py
  rdmo/options/viewsets.py
  rdmo/projects/models/value.py
  rdmo/projects/serializers/v1/page.py
  rdmo/projects/static/projects/css/project_questions.scss
  rdmo/projects/static/projects/js/project_questions/services.js
  rdmo/projects/templates/projects/project_questions_form_group_autocomplete.html
  rdmo/projects/templates/projects/project_questions_form_group_checkbox.html
  rdmo/projects/templates/projects/project_questions_form_group_radio.html
  rdmo/projects/templates/projects/project_questions_form_group_select.html
  rdmo/projects/tests/test_value.py
  testing/fixtures/options.json
  testing/xml/elements/attributes.xml
  testing/xml/elements/catalog.xml
  testing/xml/elements/catalogs.xml
  testing/xml/elements/conditions.xml
  testing/xml/elements/legacy/options.xml
  testing/xml/elements/options.xml
  testing/xml/elements/optionsets.xml
  testing/xml/elements/pages.xml
  testing/xml/elements/question-error.xml
  testing/xml/elements/question.xml
  testing/xml/elements/questions.xml
  testing/xml/elements/questionsets.xml
  testing/xml/elements/sections.xml
  testing/xml/elements/tasks.xml
  testing/xml/elements/views.xml
Labels: status:acceptance

#840 build: add the django-shibboleth-remoteuser fork #828
  .github/workflows/ci.yml
  pyproject.toml
Labels: type:maintenance, dependencies

#790 745 add order parameter
  rdmo/management/assets/js/components/common/Links.js
  rdmo/management/assets/js/components/element/Page.js
  rdmo/management/assets/js/components/element/Question.js
  rdmo/management/assets/js/components/element/QuestionSet.js
  rdmo/management/assets/js/components/element/Section.js
  rdmo/management/assets/js/components/nested/NestedCatalog.js
Labels: type:feature-request, javascript

#843 ci: remove playwright browsers caching
  .github/workflows/ci.yml
Labels: type:maintenance
