Repository rdmorganiser/rdmo, pull requests merged in 2024-08, with the labels that each got.

#1105 tests(projects): add files fixture to tests that use MEDIA_ROOT
  rdmo/projects/tests/test_view_project_create_import.py
  rdmo/projects/tests/test_view_project_update_import.py
  rdmo/projects/tests/test_view_snapshot.py
  rdmo/projects/tests/test_viewset_project_snapshot.py
Labels: type:maintenance

#1061 refactor: improve e2e test performance
  .github/workflows/ci.yml
  rdmo/management/tests/conftest.py
  rdmo/management/tests/e2e/__init__.py
  rdmo/management/tests/e2e/conftest.py
  rdmo/management/tests/e2e/test_frontend_import_options.py
  rdmo/management/tests/e2e/test_frontend_import_questions.py
  rdmo/management/tests/e2e/test_frontend_management_elements.py
  testing/manage.py
Labels: type:maintenance

#1107 Fix progress for conditional questions in datasets
  rdmo/projects/progress.py
  rdmo/projects/tests/test_navigation.py
  rdmo/projects/tests/test_progress.py
  rdmo/projects/tests/test_viewset_project_progress.py
Labels: status:work-in-progress, status:hold

#1078 Fix import element sorting when saving (for related items)
  rdmo/core/constants.py
  rdmo/core/import_helpers.py
  rdmo/core/imports.py
  rdmo/core/xml.py
  rdmo/domain/imports.py
  rdmo/management/assets/js/components/import/common/WarningsListGroup.js
  rdmo/management/import_utils.py
  rdmo/management/imports.py
  rdmo/management/tests/helpers_import_elements.py
  rdmo/management/tests/test_import_options.py
  rdmo/management/tests/test_import_questions.py
  rdmo/management/viewsets.py
  rdmo/questions/imports.py
Labels: status:acceptance

#1106 Dependency updates August 24 (2.2.0)
  .pre-commit-config.yaml
  package-lock.json
  package.json
  pyproject.toml
  rdmo/core/tests/test_package_status.py
Labels: type:maintenance, dependencies

#1120 build(pyproject): pin all current dependencies to >=min,<max ranges (#1119)
  pyproject.toml
Labels: type:maintenance, dependencies
