Repository rdmorganiser/rdmo, pull requests merged in 2025-02, with the labels that each got.

#1156 Refactor upload accept
  rdmo/core/assets/js/components/UploadDropZone.js
  rdmo/projects/assets/js/projects/actions/projectsActions.js
  rdmo/projects/assets/js/projects/components/helper/ProjectImport.js
  rdmo/projects/assets/js/projects/reducers/projectsReducer.js
  rdmo/projects/imports.py
  rdmo/projects/tests/test_viewset_project.py
  rdmo/projects/utils.py
  rdmo/projects/views/project.py
Labels: type:maintenance

#1217 Feat: add Terms of Use accept view and middleware
  rdmo/accounts/account.py
  rdmo/accounts/admin.py
  rdmo/accounts/forms.py
  rdmo/accounts/middleware.py
  rdmo/accounts/migrations/0022_add_created_updated_to_consent.py
  rdmo/accounts/models.py
  rdmo/accounts/socialaccount.py
  rdmo/accounts/templates/account/terms_of_use_accept_form.html
  rdmo/accounts/tests/helpers.py
  rdmo/accounts/tests/test_views.py
  rdmo/accounts/tests/test_views_socialaccount.py
  rdmo/accounts/tests/utils.py
  rdmo/accounts/urls/__init__.py
  rdmo/accounts/views.py
  rdmo/core/apps.py
  rdmo/core/checks.py
  rdmo/core/settings.py
  rdmo/core/tests/test_utils.py
  rdmo/core/utils.py
  rdmo/core/views.py
  testing/config/settings/base.py
Labels: type:feature-request

#1218 signal handlers for syncing of project views and tasks
  rdmo/core/settings.py
  rdmo/projects/apps.py
  rdmo/projects/forms.py
  rdmo/projects/handlers.py
  rdmo/projects/handlers/__init__.py
  rdmo/projects/handlers/generic_handlers.py
  rdmo/projects/handlers/m2m_changed_tasks.py
  rdmo/projects/handlers/m2m_changed_views.py
  rdmo/projects/handlers/project_save_tasks.py
  rdmo/projects/handlers/project_save_views.py
  rdmo/projects/managers.py
  rdmo/projects/models/project.py
  rdmo/projects/serializers/v1/__init__.py
  rdmo/projects/templates/projects/project_detail_issues.html
  rdmo/projects/templates/projects/project_detail_sidebar.html
  rdmo/projects/templates/projects/project_detail_views.html
  rdmo/projects/tests/helpers.py
  rdmo/projects/tests/test_handlers.py
  rdmo/projects/tests/test_handlers_m2m_tasks.py
  rdmo/projects/tests/test_handlers_m2m_views.py
  rdmo/projects/tests/test_handlers_project_save.py
  rdmo/projects/tests/test_view_project.py
  rdmo/projects/tests/test_viewset_project.py
  rdmo/projects/views/project.py
  rdmo/projects/views/project_create.py
  rdmo/projects/views/project_update.py
  rdmo/projects/viewsets.py
  rdmo/tasks/managers.py
  rdmo/views/managers.py
  testing/config/settings/base.py
Labels: status:work-in-progress, type:feature-request, status:acceptance

#1232 Add minimum required version to rdmo xml exports and check at import
  rdmo/conditions/renderers/__init__.py
  rdmo/core/renderers.py
  rdmo/core/settings.py
  rdmo/core/tests/test_renderers.py
  rdmo/core/xml.py
  rdmo/domain/renderers/__init__.py
  rdmo/management/tests/helpers_xml.py
  rdmo/management/tests/test_commands.py
  rdmo/options/renderers/__init__.py
  rdmo/projects/renderers.py
  rdmo/questions/renderers/__init__.py
  rdmo/tasks/renderers/__init__.py
  rdmo/views/renderers/__init__.py
  testing/xml/error-version-required.xml
  testing/xml/error-version.xml
Labels: status:work-in-progress

#1154 Dependency updates for 2.3.0
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  package-lock.json
  package.json
  pyproject.toml
  rdmo/conditions/tests/test_validator_locked.py
  rdmo/conditions/tests/test_validator_unique_uri.py
  rdmo/core/import_helpers.py
  rdmo/core/imports.py
  rdmo/core/xml.py
  rdmo/domain/tests/test_validator_locked.py
  rdmo/domain/tests/test_validator_parent.py
  rdmo/domain/tests/test_validator_unique_uri.py
  rdmo/management/import_utils.py
  rdmo/management/imports.py
  rdmo/management/tests/helpers_import_elements.py
  rdmo/management/tests/helpers_models.py
  rdmo/management/tests/test_merge_attributes.py
  rdmo/options/tests/test_validator_locked_options.py
  rdmo/options/tests/test_validator_locked_optionsets.py
  rdmo/options/tests/test_validator_unique_uri_options.py
  rdmo/options/tests/test_validator_unique_uri_optionsets.py
  rdmo/projects/tests/test_validator_conflict.py
  rdmo/projects/tests/test_validator_quota.py
  rdmo/projects/tests/test_validator_value_type.py
  rdmo/questions/tests/test_validator_locked_catalogs.py
  rdmo/questions/tests/test_validator_locked_pages.py
  rdmo/questions/tests/test_validator_locked_questions.py
  rdmo/questions/tests/test_validator_locked_questionsets.py
  rdmo/questions/tests/test_validator_locked_sections.py
  rdmo/questions/tests/test_validator_unique_uri_catalogs.py
  rdmo/questions/tests/test_validator_unique_uri_pages.py
  rdmo/questions/tests/test_validator_unique_uri_questions.py
  rdmo/questions/tests/test_validator_unique_uri_questionsets.py
  rdmo/questions/tests/test_validator_unique_uri_sections.py
  rdmo/tasks/tests/test_validator_locked.py
  rdmo/tasks/tests/test_validator_unique_uri.py
  rdmo/views/tests/test_validator_locked.py
  rdmo/views/tests/test_validator_unique_uri.py
  webpack.config.js
Labels: type:maintenance
